package com.trymeyourself.foodapperp.controller;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

//ctrl + shift + o to import the restcontroller

@RestController
public class HomeController {
	
	
	@GetMapping("/home")
	public String index() {
		return "<!DOCTYPE html>\r\n"
				+ "<html lang=\"en\">\r\n"
				+ "<head>\r\n"
				+ "    <meta charset=\"UTF-8\">\r\n"
				+ "    <title>ABC College</title>\r\n"
				+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n"
				+ "\r\n"
				+ "    <!-- Bootstrap 5 CSS -->\r\n"
				+ "    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n"
				+ "\r\n"
				+ "    <style>\r\n"
				+ "        .hero-section {\r\n"
				+ "            background: url('https://images.unsplash.com/photo-1562774053-701939374585') no-repeat center center/cover;\r\n"
				+ "            height: 90vh;\r\n"
				+ "            color: white;\r\n"
				+ "            display: flex;\r\n"
				+ "            align-items: center;\r\n"
				+ "            justify-content: center;\r\n"
				+ "            text-align: center;\r\n"
				+ "        }\r\n"
				+ "        .hero-overlay {\r\n"
				+ "            background: rgba(0,0,0,0.6);\r\n"
				+ "            padding: 50px;\r\n"
				+ "            border-radius: 10px;\r\n"
				+ "        }\r\n"
				+ "        .card img {\r\n"
				+ "            height: 200px;\r\n"
				+ "            object-fit: cover;\r\n"
				+ "        }\r\n"
				+ "        footer {\r\n"
				+ "            background-color: #212529;\r\n"
				+ "            color: white;\r\n"
				+ "            padding: 20px 0;\r\n"
				+ "        }\r\n"
				+ "    </style>\r\n"
				+ "</head>\r\n"
				+ "<body>\r\n"
				+ "\r\n"
				+ "<!-- Navbar -->\r\n"
				+ "<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\r\n"
				+ "    <div class=\"container\">\r\n"
				+ "        <a class=\"navbar-brand\" href=\"#\">ABC College</a>\r\n"
				+ "        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\">\r\n"
				+ "            <span class=\"navbar-toggler-icon\"></span>\r\n"
				+ "        </button>\r\n"
				+ "        <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n"
				+ "            <ul class=\"navbar-nav ms-auto\">\r\n"
				+ "                <li class=\"nav-item\"><a class=\"nav-link active\" href=\"#\">Home</a></li>\r\n"
				+ "                <li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">About</a></li>\r\n"
				+ "                <li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Courses</a></li>\r\n"
				+ "                <li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Admissions</a></li>\r\n"
				+ "                <li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Contact</a></li>\r\n"
				+ "            </ul>\r\n"
				+ "        </div>\r\n"
				+ "    </div>\r\n"
				+ "</nav>\r\n"
				+ "\r\n"
				+ "<!-- Hero Section -->\r\n"
				+ "<section class=\"hero-section\">\r\n"
				+ "    <div class=\"hero-overlay\">\r\n"
				+ "        <h1 class=\"display-4 fw-bold\">Welcome to ABC College</h1>\r\n"
				+ "        <p class=\"lead\">Empowering Students for a Brighter Future</p>\r\n"
				+ "        <a href=\"#\" class=\"btn btn-primary btn-lg mt-3\">Apply Now</a>\r\n"
				+ "    </div>\r\n"
				+ "</section>\r\n"
				+ "\r\n"
				+ "<!-- About Section -->\r\n"
				+ "<section class=\"py-5\">\r\n"
				+ "    <div class=\"container\">\r\n"
				+ "        <div class=\"text-center mb-4\">\r\n"
				+ "            <h2>About Our College</h2>\r\n"
				+ "            <p class=\"text-muted\">Committed to excellence in education</p>\r\n"
				+ "        </div>\r\n"
				+ "        <div class=\"row align-items-center\">\r\n"
				+ "            <div class=\"col-md-6\">\r\n"
				+ "                <img src=\"https://images.unsplash.com/photo-1523050854058-8df90110c9f1\" class=\"img-fluid rounded\" alt=\"College\">\r\n"
				+ "            </div>\r\n"
				+ "            <div class=\"col-md-6\">\r\n"
				+ "                <p>\r\n"
				+ "                    ABC College provides world-class education with experienced faculty, modern infrastructure,\r\n"
				+ "                    and industry-focused curriculum. Our mission is to nurture talent and shape future leaders.\r\n"
				+ "                </p>\r\n"
				+ "                <a href=\"#\" class=\"btn btn-outline-primary\">Read More</a>\r\n"
				+ "            </div>\r\n"
				+ "        </div>\r\n"
				+ "    </div>\r\n"
				+ "</section>\r\n"
				+ "\r\n"
				+ "<!-- Courses Section -->\r\n"
				+ "<section class=\"bg-light py-5\">\r\n"
				+ "    <div class=\"container\">\r\n"
				+ "        <div class=\"text-center mb-4\">\r\n"
				+ "            <h2>Our Courses</h2>\r\n"
				+ "        </div>\r\n"
				+ "        <div class=\"row g-4\">\r\n"
				+ "\r\n"
				+ "            <div class=\"col-md-4\">\r\n"
				+ "                <div class=\"card shadow-sm\">\r\n"
				+ "                    <img src=\"https://images.unsplash.com/photo-1519389950473-47ba0277781c\" class=\"card-img-top\" alt=\"Computer Science\">\r\n"
				+ "                    <div class=\"card-body\">\r\n"
				+ "                        <h5 class=\"card-title\">Computer Science</h5>\r\n"
				+ "                        <p class=\"card-text\">Learn programming, AI, cybersecurity and software development.</p>\r\n"
				+ "                        <a href=\"#\" class=\"btn btn-primary btn-sm\">Learn More</a>\r\n"
				+ "                    </div>\r\n"
				+ "                </div>\r\n"
				+ "            </div>\r\n"
				+ "\r\n"
				+ "            <div class=\"col-md-4\">\r\n"
				+ "                <div class=\"card shadow-sm\">\r\n"
				+ "                    <img src=\"https://images.unsplash.com/photo-1503676260728-1c00da094a0b\" class=\"card-img-top\" alt=\"Business Management\">\r\n"
				+ "                    <div class=\"card-body\">\r\n"
				+ "                        <h5 class=\"card-title\">Business Management</h5>\r\n"
				+ "                        <p class=\"card-text\">Develop leadership and entrepreneurial skills for global markets.</p>\r\n"
				+ "                        <a href=\"#\" class=\"btn btn-primary btn-sm\">Learn More</a>\r\n"
				+ "                    </div>\r\n"
				+ "                </div>\r\n"
				+ "            </div>\r\n"
				+ "\r\n"
				+ "            <div class=\"col-md-4\">\r\n"
				+ "                <div class=\"card shadow-sm\">\r\n"
				+ "                    <img src=\"https://images.unsplash.com/photo-1581090700227-1e37b190418e\" class=\"card-img-top\" alt=\"Engineering\">\r\n"
				+ "                    <div class=\"card-body\">\r\n"
				+ "                        <h5 class=\"card-title\">Engineering</h5>\r\n"
				+ "                        <p class=\"card-text\">Hands-on technical education with real-world project exposure.</p>\r\n"
				+ "                        <a href=\"#\" class=\"btn btn-primary btn-sm\">Learn More</a>\r\n"
				+ "                    </div>\r\n"
				+ "                </div>\r\n"
				+ "            </div>\r\n"
				+ "\r\n"
				+ "        </div>\r\n"
				+ "    </div>\r\n"
				+ "</section>\r\n"
				+ "\r\n"
				+ "<!-- Facilities Section -->\r\n"
				+ "<section class=\"py-5\">\r\n"
				+ "    <div class=\"container\">\r\n"
				+ "        <div class=\"text-center mb-4\">\r\n"
				+ "            <h2>Our Facilities</h2>\r\n"
				+ "        </div>\r\n"
				+ "        <div class=\"row text-center g-4\">\r\n"
				+ "            <div class=\"col-md-3\">\r\n"
				+ "                <img src=\"https://images.unsplash.com/photo-1497633762265-9d179a990aa6\" class=\"img-fluid rounded mb-2\" alt=\"Library\">\r\n"
				+ "                <h5>Modern Library</h5>\r\n"
				+ "            </div>\r\n"
				+ "            <div class=\"col-md-3\">\r\n"
				+ "                <img src=\"https://images.unsplash.com/photo-1588072432836-e10032774350\" class=\"img-fluid rounded mb-2\" alt=\"Laboratory\">\r\n"
				+ "                <h5>Advanced Labs</h5>\r\n"
				+ "            </div>\r\n"
				+ "            <div class=\"col-md-3\">\r\n"
				+ "                <img src=\"https://images.unsplash.com/photo-1596495578065-6e0763fa1178\" class=\"img-fluid rounded mb-2\" alt=\"Sports\">\r\n"
				+ "                <h5>Sports Complex</h5>\r\n"
				+ "            </div>\r\n"
				+ "            <div class=\"col-md-3\">\r\n"
				+ "                <img src=\"https://images.unsplash.com/photo-1557683316-973673baf926\" class=\"img-fluid rounded mb-2\" alt=\"Campus\">\r\n"
				+ "                <h5>Beautiful Campus</h5>\r\n"
				+ "            </div>\r\n"
				+ "        </div>\r\n"
				+ "    </div>\r\n"
				+ "</section>\r\n"
				+ "\r\n"
				+ "<!-- Contact Section -->\r\n"
				+ "<section class=\"bg-light py-5\">\r\n"
				+ "    <div class=\"container\">\r\n"
				+ "        <div class=\"text-center mb-4\">\r\n"
				+ "            <h2>Contact Us</h2>\r\n"
				+ "        </div>\r\n"
				+ "        <div class=\"row\">\r\n"
				+ "            <div class=\"col-md-6\">\r\n"
				+ "                <h5>Get in Touch</h5>\r\n"
				+ "                <p>Email: info@abccollege.edu</p>\r\n"
				+ "                <p>Phone: +1 234 567 890</p>\r\n"
				+ "                <p>Address: 123 College Road, City, Country</p>\r\n"
				+ "            </div>\r\n"
				+ "            <div class=\"col-md-6\">\r\n"
				+ "                <form>\r\n"
				+ "                    <div class=\"mb-3\">\r\n"
				+ "                        <input type=\"text\" class=\"form-control\" placeholder=\"Your Name\">\r\n"
				+ "                    </div>\r\n"
				+ "                    <div class=\"mb-3\">\r\n"
				+ "                        <input type=\"email\" class=\"form-control\" placeholder=\"Your Email\">\r\n"
				+ "                    </div>\r\n"
				+ "                    <div class=\"mb-3\">\r\n"
				+ "                        <textarea class=\"form-control\" rows=\"4\" placeholder=\"Your Message\"></textarea>\r\n"
				+ "                    </div>\r\n"
				+ "                    <button class=\"btn btn-primary\">Send Message</button>\r\n"
				+ "                </form>\r\n"
				+ "            </div>\r\n"
				+ "        </div>\r\n"
				+ "    </div>\r\n"
				+ "</section>\r\n"
				+ "\r\n"
				+ "<!-- Footer -->\r\n"
				+ "<footer class=\"text-center\">\r\n"
				+ "    <div class=\"container\">\r\n"
				+ "        <p class=\"mb-0\">© 2026 ABC College. All Rights Reserved.</p>\r\n"
				+ "    </div>\r\n"
				+ "</footer>\r\n"
				+ "\r\n"
				+ "<!-- Bootstrap JS -->\r\n"
				+ "<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n"
				+ "\r\n"
				+ "</body>\r\n"
				+ "</html>";
	}

}
